"""add state_read to permissions

Revision ID: 1956e9dbf6ff
Revises: e83364fd2be3
Create Date: 2026-08-15 15:11:33.521336

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1956e9dbf6ff'
down_revision: Union[str, Sequence[str], None] = 'e83364fd2be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE permission ADD VALUE 'state_read'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###
