"""add refresh token fields to sessions

Revision ID: 21e7ac0e0753
Revises: cd33c24d190b
Create Date: 2026-05-14 08:57:05.163677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21e7ac0e0753'
down_revision: Union[str, Sequence[str], None] = 'cd33c24d190b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('refreshed_at', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('sessions', sa.Column('refresh_token_hmac_key', sa.Text(), nullable=False))
    op.add_column('sessions', sa.Column('refresh_token_counter', sa.BIGINT(), nullable=False))
    op.drop_column('sessions', 'last_seen_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('sessions', 'refresh_token_counter')
    op.drop_column('sessions', 'refresh_token_hmac_key')
    op.drop_column('sessions', 'refreshed_at')
    # ### end Alembic commands ###
