"""make revision counter based

Revision ID: 261a57a0bc67
Revises: 1956e9dbf6ff
Create Date: 2026-08-16 11:16:36.883175

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from alembic_utils.pg_trigger import PGTrigger

# revision identifiers, used by Alembic.
revision: str = "261a57a0bc67"
down_revision: Union[str, Sequence[str], None] = "1956e9dbf6ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_allocate_revision = PGFunction(
        schema="public",
        signature="allocate_revision(user_id uuid)",
        definition="RETURNS BIGINT AS $$\n    DECLARE\n        cached_revision TEXT := NULLIF(CURRENT_SETTING('aoi.revision', TRUE), '');\n        allocated_revision BIGINT;\n    BEGIN\n        IF cached_revision IS NOT NULL THEN\n            RETURN cached_revision::BIGINT;\n        END IF; \n\n        UPDATE users\n        SET last_revision = last_revision + 1\n        WHERE id = user_id\n        RETURNING last_revision INTO allocated_revision;\n\n        IF allocated_revision IS NULL THEN\n            RAISE EXCEPTION 'Cannot allocate revision for user % because it does not exist', user_id;\n        END IF;\n\n        PERFORM SET_CONFIG('aoi.revision', allocated_revision::TEXT ,TRUE);\n\n        RETURN allocated_revision;\n    END\n    $$ LANGUAGE plpgsql VOLATILE",
    )
    op.create_entity(public_allocate_revision)

    public_initialize_user_revision = PGFunction(
        schema="public",
        signature="initialize_user_revision()",
        definition="RETURNS BIGINT AS $$\n    BEGIN\n      PERFORM SET_CONFIG('aoi.revision', '1', TRUE);\n      RETURN 1;\n    END\n    $$ LANGUAGE plpgsql VOLATILE",
    )
    op.create_entity(public_initialize_user_revision)

    public_advance_user_revision = PGFunction(
        schema="public",
        signature="advance_user_revision()",
        definition="RETURNS TRIGGER AS $$\n    DECLARE \n        cached_revision TEXT := NULLIF(CURRENT_SETTING('aoi.revision', TRUE), '');\n        allocated_revision BIGINT;\n    BEGIN\n        IF cached_revision IS NOT NULL THEN\n            allocated_revision := cached_revision::BIGINT;\n        ELSE\n            allocated_revision := OLD.last_revision + 1;\n            PERFORM SET_CONFIG('aoi.revision', allocated_revision::TEXT, TRUE);\n        END IF;\n\n        NEW.last_revision := allocated_revision;\n        NEW.revision := allocated_revision;\n\n        RETURN NEW;\n    END\n    $$ LANGUAGE plpgsql VOLATILE",
    )
    op.create_entity(public_advance_user_revision)

    public_advance_owned_model_revision = PGFunction(
        schema="public",
        signature="advance_owned_model_revision()",
        definition="RETURNS TRIGGER AS $$\n    BEGIN\n        NEW.revision := allocate_revision(NEW.user_id);\n        RETURN NEW;\n    END\n    $$ LANGUAGE plpgsql VOLATILE",
    )
    op.create_entity(public_advance_owned_model_revision)

    public_sessions_record_session_deletions = PGTrigger(
        schema="public",
        signature="record_session_deletions",
        on_entity="public.sessions",
        is_constraint=False,
        definition="AFTER DELETE ON sessions\n    REFERENCING OLD TABLE AS deleted_rows\n    FOR EACH STATEMENT\n    EXECUTE FUNCTION record_deletions('session')",
    )
    op.create_entity(public_sessions_record_session_deletions)

    public_personal_access_tokens_record_personal_access_token_deletions = PGTrigger(
        schema="public",
        signature="record_personal_access_token_deletions",
        on_entity="public.personal_access_tokens",
        is_constraint=False,
        definition="AFTER DELETE ON personal_access_tokens\n    REFERENCING OLD TABLE AS deleted_rows\n    FOR EACH STATEMENT\n    EXECUTE FUNCTION record_deletions('personal_access_token')",
    )
    op.create_entity(
        public_personal_access_tokens_record_personal_access_token_deletions
    )

    public_record_deletions = PGFunction(
        schema="public",
        signature="record_deletions()",
        definition="RETURNS TRIGGER AS $$\n    DECLARE\n        allocated_revision BIGINT;\n    BEGIN\n        SELECT allocate_revision(user_id)\n        INTO allocated_revision\n        FROM deleted_rows\n        LIMIT 1;\n\n        INSERT INTO deletions (model_name, model_id, user_id, revision)\n        SELECT TG_ARGV[0]::deleted_model, id, user_id, allocated_revision\n        FROM deleted_rows;\n\n        RETURN NULL;\n    END\n    $$ LANGUAGE plpgsql VOLATILE",
    )
    op.replace_entity(public_record_deletions)

    public_sessions_advance_session_revision = PGTrigger(
        schema="public",
        signature="advance_session_revision",
        on_entity="public.sessions",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON sessions\n    FOR EACH ROW\n    EXECUTE FUNCTION advance_owned_model_revision()",
    )
    op.create_entity(public_sessions_advance_session_revision)

    public_personal_access_tokens_advance_personal_access_token_revision = PGTrigger(
        schema="public",
        signature="advance_personal_access_token_revision",
        on_entity="public.personal_access_tokens",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON personal_access_tokens\n    FOR EACH ROW\n    EXECUTE FUNCTION advance_owned_model_revision()",
    )
    op.create_entity(
        public_personal_access_tokens_advance_personal_access_token_revision
    )

    public_users_advance_user_revision = PGTrigger(
        schema="public",
        signature="advance_user_revision",
        on_entity="public.users",
        is_constraint=False,
        definition="BEFORE UPDATE OF email, name ON users\n    FOR EACH ROW\n    WHEN (\n        OLD.email IS DISTINCT FROM NEW.email\n        OR OLD.name IS DISTINCT FROM NEW.name\n    )\n    EXECUTE FUNCTION advance_user_revision()",
    )
    op.create_entity(public_users_advance_user_revision)

    public_sessions_session_deletion = PGTrigger(
        schema="public",
        signature="session_deletion",
        on_entity="public.sessions",
        is_constraint=False,
        definition="AFTER DELETE ON public.sessions REFERENCING OLD TABLE AS deleted_rows FOR EACH STATEMENT EXECUTE FUNCTION record_deletions('session')",
    )
    op.drop_entity(public_sessions_session_deletion)

    public_personal_access_tokens_personal_access_token_deletions = PGTrigger(
        schema="public",
        signature="personal_access_token_deletions",
        on_entity="public.personal_access_tokens",
        is_constraint=False,
        definition="AFTER DELETE ON public.personal_access_tokens REFERENCING OLD TABLE AS deleted_rows FOR EACH STATEMENT EXECUTE FUNCTION record_deletions('personal_access_token')",
    )
    op.drop_entity(public_personal_access_tokens_personal_access_token_deletions)

    op.add_column("deletions", sa.Column("user_id", sa.UUID(), nullable=False))
    op.add_column(
        "users",
        sa.Column(
            "last_revision",
            sa.BIGINT(),
            server_default=sa.text("initialize_user_revision()"),
            nullable=False,
        ),
    )

    op.alter_column(
        "users",
        "revision",
        existing_type=sa.BIGINT(),
        server_default=sa.text("1"),
        existing_nullable=False,
    )
    op.alter_column(
        "sessions",
        "revision",
        existing_type=sa.BIGINT(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "personal_access_tokens",
        "revision",
        existing_type=sa.BIGINT(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "deletions",
        "revision",
        existing_type=sa.BIGINT(),
        server_default=None,
        existing_nullable=False,
    )

    op.execute("DROP SEQUENCE revision_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE SEQUENCE revision_number
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 100
    """)

    revision_sequence_default = sa.text("nextval('revision_number')")
    for table_name in (
        "users",
        "sessions",
        "personal_access_tokens",
        "deletions",
    ):
        op.alter_column(
            table_name,
            "revision",
            existing_type=sa.BIGINT(),
            server_default=revision_sequence_default,
            existing_nullable=False,
        )

    op.drop_column("users", "last_revision")
    op.drop_column("deletions", "user_id")
    public_personal_access_tokens_personal_access_token_deletions = PGTrigger(
        schema="public",
        signature="personal_access_token_deletions",
        on_entity="public.personal_access_tokens",
        is_constraint=False,
        definition="AFTER DELETE ON public.personal_access_tokens REFERENCING OLD TABLE AS deleted_rows FOR EACH STATEMENT EXECUTE FUNCTION record_deletions('personal_access_token')",
    )
    op.create_entity(public_personal_access_tokens_personal_access_token_deletions)

    public_sessions_session_deletion = PGTrigger(
        schema="public",
        signature="session_deletion",
        on_entity="public.sessions",
        is_constraint=False,
        definition="AFTER DELETE ON public.sessions REFERENCING OLD TABLE AS deleted_rows FOR EACH STATEMENT EXECUTE FUNCTION record_deletions('session')",
    )
    op.create_entity(public_sessions_session_deletion)

    public_users_advance_user_revision = PGTrigger(
        schema="public",
        signature="advance_user_revision",
        on_entity="public.users",
        is_constraint=False,
        definition="BEFORE UPDATE OF email, name ON users\n    FOR EACH ROW\n    WHEN (\n        OLD.email IS DISTINCT FROM NEW.email\n        OR OLD.name IS DISTINCT FROM NEW.name\n    )\n    EXECUTE FUNCTION advance_user_revision()",
    )
    op.drop_entity(public_users_advance_user_revision)

    public_personal_access_tokens_advance_personal_access_token_revision = PGTrigger(
        schema="public",
        signature="advance_personal_access_token_revision",
        on_entity="public.personal_access_tokens",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON personal_access_tokens\n    FOR EACH ROW\n    EXECUTE FUNCTION advance_owned_model_revision()",
    )
    op.drop_entity(public_personal_access_tokens_advance_personal_access_token_revision)

    public_sessions_advance_session_revision = PGTrigger(
        schema="public",
        signature="advance_session_revision",
        on_entity="public.sessions",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON sessions\n    FOR EACH ROW\n    EXECUTE FUNCTION advance_owned_model_revision()",
    )
    op.drop_entity(public_sessions_advance_session_revision)

    public_record_deletions = PGFunction(
        schema="public",
        signature="record_deletions()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n        BEGIN\n            INSERT INTO deletions (model_name, model_id)\n            SELECT TG_ARGV[0]::deleted_model, id\n            FROM deleted_rows;\n\n            RETURN NULL;\n        END\n        $function$",
    )
    op.replace_entity(public_record_deletions)
    public_personal_access_tokens_record_personal_access_token_deletions = PGTrigger(
        schema="public",
        signature="record_personal_access_token_deletions",
        on_entity="public.personal_access_tokens",
        is_constraint=False,
        definition="AFTER DELETE ON personal_access_tokens\n    REFERENCING OLD TABLE AS deleted_rows\n    FOR EACH STATEMENT\n    EXECUTE FUNCTION record_deletions('personal_access_token')",
    )
    op.drop_entity(public_personal_access_tokens_record_personal_access_token_deletions)

    public_sessions_record_session_deletions = PGTrigger(
        schema="public",
        signature="record_session_deletions",
        on_entity="public.sessions",
        is_constraint=False,
        definition="AFTER DELETE ON sessions\n    REFERENCING OLD TABLE AS deleted_rows\n    FOR EACH STATEMENT\n    EXECUTE FUNCTION record_deletions('session')",
    )
    op.drop_entity(public_sessions_record_session_deletions)

    public_advance_owned_model_revision = PGFunction(
        schema="public",
        signature="advance_owned_model_revision()",
        definition="RETURNS TRIGGER AS $$\n    BEGIN\n        NEW.revision := allocate_revision(NEW.user_id);\n        RETURN NEW;\n    END\n    $$ LANGUAGE plpgsql VOLATILE",
    )
    op.drop_entity(public_advance_owned_model_revision)

    public_advance_user_revision = PGFunction(
        schema="public",
        signature="advance_user_revision()",
        definition="RETURNS TRIGGER AS $$\n    DECLARE \n        cached_revision TEXT := NULLIF(CURRENT_SETTING('aoi.revision', TRUE), '');\n        allocated_revision BIGINT;\n    BEGIN\n        IF cached_revision IS NOT NULL THEN\n            allocated_revision := cached_revision::BIGINT;\n        ELSE\n            allocated_revision := OLD.last_revision + 1;\n            PERFORM SET_CONFIG('aoi.revision', allocated_revision::TEXT, TRUE);\n        END IF;\n\n        NEW.last_revision := allocated_revision;\n        NEW.revision := allocated_revision;\n\n        RETURN NEW;\n    END\n    $$ LANGUAGE plpgsql VOLATILE",
    )
    op.drop_entity(public_advance_user_revision)

    public_initialize_user_revision = PGFunction(
        schema="public",
        signature="initialize_user_revision()",
        definition="RETURNS BIGINT AS $$\n    BEGIN\n      PERFORM SET_CONFIG('aoi.revision', '1', TRUE);\n      RETURN 1;\n    END\n    $$ LANGUAGE plpgsql VOLATILE",
    )
    op.drop_entity(public_initialize_user_revision)

    public_allocate_revision = PGFunction(
        schema="public",
        signature="allocate_revision(user_id uuid)",
        definition="RETURNS BIGINT AS $$\n    DECLARE\n        cached_revision TEXT := NULLIF(CURRENT_SETTING('aoi.revision', TRUE), '');\n        allocated_revision BIGINT;\n    BEGIN\n        IF cached_revision IS NOT NULL THEN\n            RETURN cached_revision::BIGINT;\n        END IF; \n\n        UPDATE users\n        SET last_revision = last_revision + 1\n        WHERE id = user_id\n        RETURNING last_revision INTO allocated_revision;\n\n        IF allocated_revision IS NULL THEN\n            RAISE EXCEPTION 'Cannot allocate revision for user % because it does not exist', user_id;\n        END IF;\n\n        PERFORM SET_CONFIG('aoi.revision', allocated_revision::TEXT ,TRUE);\n\n        RETURN allocated_revision;\n    END\n    $$ LANGUAGE plpgsql VOLATILE",
    )
    op.drop_entity(public_allocate_revision)

    # ### end Alembic commands ###
