"""remove was used from login tokens and add unique constraint

Revision ID: 6f2e6b964f03
Revises: 261a57a0bc67
Create Date: 2026-08-16 12:23:48.703468

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f2e6b964f03"
down_revision: Union[str, Sequence[str], None] = "261a57a0bc67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("login_tokens_token_hash_email_key"),
        "login_tokens",
        ["token_hash", "email"],
    )
    op.drop_column("login_tokens", "was_used")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "login_tokens",
        sa.Column(
            "was_used",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column("login_tokens", "was_used", server_default=None)
    op.drop_constraint(
        op.f("login_tokens_token_hash_email_key"), "login_tokens", type_="unique"
    )
    # ### end Alembic commands ###
