"""create personal access tokens

Revision ID: 7d8fc04d2a20
Revises: 21e7ac0e0753
Create Date: 2026-06-03 12:34:24.427818

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d8fc04d2a20"
down_revision: Union[str, Sequence[str], None] = "21e7ac0e0753"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personal_access_tokens",
        sa.Column("token_hash", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "permissions",
            sa.ARRAY(
                sa.Enum(
                    "user_read",
                    "user_write",
                    "sessions_read",
                    "sessions_write",
                    "personal_access_tokens_read",
                    "personal_access_tokens_write",
                    "links_read",
                    "links_write",
                    name="permission",
                )
            ),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("revoked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("personal_access_tokens_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("personal_access_tokens_pkey")),
        sa.UniqueConstraint(
            "token_hash", name=op.f("personal_access_tokens_token_hash_key")
        ),
    )
    op.create_index(
        op.f("ix_personal_access_tokens_created_at"),
        "personal_access_tokens",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_personal_access_tokens_expires_at"),
        "personal_access_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_personal_access_tokens_revoked_at"),
        "personal_access_tokens",
        ["revoked_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_personal_access_tokens_user_id"),
        "personal_access_tokens",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_personal_access_tokens_user_id"), table_name="personal_access_tokens"
    )
    op.drop_index(
        op.f("ix_personal_access_tokens_revoked_at"),
        table_name="personal_access_tokens",
    )
    op.drop_index(
        op.f("ix_personal_access_tokens_expires_at"),
        table_name="personal_access_tokens",
    )
    op.drop_index(
        op.f("ix_personal_access_tokens_created_at"),
        table_name="personal_access_tokens",
    )
    op.drop_table("personal_access_tokens")
    # ### end Alembic commands ###
