"""add revision to sessions

Revision ID: 8ecb7d4b9a0d
Revises: 23c4dc3c61c1
Create Date: 2026-07-30 13:40:15.887229

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ecb7d4b9a0d"
down_revision: Union[str, Sequence[str], None] = "23c4dc3c61c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column(
            "revision",
            sa.BIGINT(),
            server_default=sa.text("nextval('revision_number')"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "revision")
    # ### end Alembic commands ###
