"""create select or insert user function

Revision ID: 98352ae50590
Revises: 6f2e6b964f03
Create Date: 2026-08-17 11:07:08.068734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction

# revision identifiers, used by Alembic.
revision: str = "98352ae50590"
down_revision: Union[str, Sequence[str], None] = "6f2e6b964f03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "last_revision", server_default=sa.text("1"))

    public_select_or_insert_user = PGFunction(
        schema="public",
        signature="select_or_insert_user(p_id UUID, p_email CITEXT, p_created_at TIMESTAMPTZ)",
        definition="RETURNS users AS $$\n    DECLARE\n        result users%ROWTYPE;\n    BEGIN\n        INSERT INTO users (id, email, created_at)\n        VALUES (p_id, p_email, p_created_at)\n        ON CONFLICT (email) DO NOTHING\n        RETURNING * INTO result;\n\n        IF FOUND THEN\n            PERFORM SET_CONFIG('aoi.revision', '1', TRUE);\n            RETURN result;\n        END IF;\n\n        SELECT *\n        INTO STRICT result\n        FROM users\n        WHERE email = p_email;\n\n        RETURN result;\n    END\n    $$ LANGUAGE plpgsql VOLATILE",
    )
    op.create_entity(public_select_or_insert_user)

    public_initialize_user_revision = PGFunction(
        schema="public",
        signature="initialize_user_revision()",
        definition="returns bigint\n LANGUAGE plpgsql\nAS $function$\n    BEGIN\n      PERFORM SET_CONFIG('aoi.revision', '1', TRUE);\n      RETURN 1;\n    END\n    $function$",
    )
    op.drop_entity(public_initialize_user_revision)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_initialize_user_revision = PGFunction(
        schema="public",
        signature="initialize_user_revision()",
        definition="returns bigint\n LANGUAGE plpgsql\nAS $function$\n    BEGIN\n      PERFORM SET_CONFIG('aoi.revision', '1', TRUE);\n      RETURN 1;\n    END\n    $function$",
    )
    op.create_entity(public_initialize_user_revision)

    public_select_or_insert_user = PGFunction(
        schema="public",
        signature="select_or_insert_user(p_id UUID, p_email CITEXT, p_created_at TIMESTAMPTZ)",
        definition="RETURNS users AS $$\n    DECLARE\n        result users%ROWTYPE;\n    BEGIN\n        INSERT INTO users (id, email, created_at)\n        VALUES (p_id, p_email, p_created_at)\n        ON CONFLICT (email) DO NOTHING\n        RETURNING * INTO result;\n\n        IF FOUND THEN\n            PERFORM SET_CONFIG('aoi.revision', '1', TRUE);\n            RETURN result;\n        END IF;\n\n        SELECT *\n        INTO STRICT result\n        FROM users\n        WHERE email = p_email;\n\n        RETURN result;\n    END\n    $$ LANGUAGE plpgsql VOLATILE",
    )
    op.drop_entity(public_select_or_insert_user)

    op.alter_column(
        "users", "last_revision", server_default=sa.text("initialize_user_revision()")
    )

    # ### end Alembic commands ###
