"""create deletions

Revision ID: b9401279c5aa
Revises: ff6177c7ea63
Create Date: 2026-08-05 18:43:12.487978

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from alembic_utils.pg_trigger import PGTrigger

# revision identifiers, used by Alembic.
revision: str = "b9401279c5aa"
down_revision: Union[str, Sequence[str], None] = "ff6177c7ea63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_record_deletions = PGFunction(
        schema="public",
        signature="record_deletions()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            INSERT INTO deletions (model_name, model_id)\n            SELECT TG_ARGV[0]::deleted_model, id\n            FROM deleted_rows;\n\n            RETURN NULL;\n        END\n        $$ LANGUAGE plpgsql",
    )
    op.create_entity(public_record_deletions)

    public_sessions_session_deletion = PGTrigger(
        schema="public",
        signature="session_deletion",
        on_entity="public.sessions",
        is_constraint=False,
        definition="AFTER DELETE ON sessions\n    REFERENCING OLD TABLE AS deleted_rows\n    FOR EACH STATEMENT\n    EXECUTE FUNCTION record_deletions('session')",
    )
    op.create_entity(public_sessions_session_deletion)

    public_personal_access_tokens_personal_access_token_deletions = PGTrigger(
        schema="public",
        signature="personal_access_token_deletions",
        on_entity="public.personal_access_tokens",
        is_constraint=False,
        definition="AFTER DELETE ON personal_access_tokens\n    REFERENCING OLD TABLE AS deleted_rows\n    FOR EACH STATEMENT\n    EXECUTE FUNCTION record_deletions('personal_access_token')",
    )
    op.create_entity(public_personal_access_tokens_personal_access_token_deletions)

    op.create_table(
        "deletions",
        sa.Column("model_id", sa.UUID(), nullable=False),
        sa.Column(
            "model_name",
            sa.Enum("session", "personal_access_token", name="deleted_model"),
            nullable=False,
        ),
        sa.Column(
            "revision",
            sa.BIGINT(),
            server_default=sa.text("nextval('revision_number')"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("model_id", "model_name", name=op.f("deletions_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deletions")
    public_personal_access_tokens_personal_access_token_deletions = PGTrigger(
        schema="public",
        signature="personal_access_token_deletions",
        on_entity="public.personal_access_tokens",
        is_constraint=False,
        definition="AFTER DELETE ON personal_access_tokens\n    REFERENCING OLD TABLE AS deleted_rows\n    FOR EACH STATEMENT\n    EXECUTE FUNCTION record_deletions('personal_access_token')",
    )
    op.drop_entity(public_personal_access_tokens_personal_access_token_deletions)

    public_sessions_session_deletion = PGTrigger(
        schema="public",
        signature="session_deletion",
        on_entity="public.sessions",
        is_constraint=False,
        definition="AFTER DELETE ON sessions\n    REFERENCING OLD TABLE AS deleted_rows\n    FOR EACH STATEMENT\n    EXECUTE FUNCTION record_deletions('session')",
    )
    op.drop_entity(public_sessions_session_deletion)

    public_record_deletions = PGFunction(
        schema="public",
        signature="record_deletions()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            INSERT INTO deletions (model_name, model_id)\n            SELECT TG_ARGV[0]::deleted_model, id\n            FROM deleted_rows;\n\n            RETURN NULL;\n        END\n        $$ LANGUAGE plpgsql",
    )
    op.drop_entity(public_record_deletions)

    # ### end Alembic commands ###
