"""remove oauth accounts

Revision ID: e2e683bfd9e6
Revises: 7d8fc04d2a20
Create Date: 2026-06-25 11:43:25.417726

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e2e683bfd9e6"
down_revision: Union[str, Sequence[str], None] = "7d8fc04d2a20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_user_id_platform"), table_name="oauth_accounts")
    op.drop_index(op.f("ix_oauth_accounts_created_at"), table_name="oauth_accounts")
    op.drop_table("oauth_accounts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_accounts",
        sa.Column(
            "platform", sa.VARCHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.Column(
            "access_token", sa.VARCHAR(length=1024), autoincrement=False, nullable=False
        ),
        sa.Column("expires_at", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "refresh_token", sa.VARCHAR(length=1024), autoincrement=False, nullable=True
        ),
        sa.Column(
            "refresh_token_expires_at", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "account_id", sa.VARCHAR(length=320), autoincrement=False, nullable=False
        ),
        sa.Column(
            "account_email", sa.VARCHAR(length=320), autoincrement=False, nullable=False
        ),
        sa.Column(
            "account_username",
            sa.VARCHAR(length=320),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("oauth_accounts_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("oauth_accounts_pkey")),
        sa.UniqueConstraint(
            "platform",
            "account_id",
            name=op.f("oauth_accounts_platform_account_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_oauth_accounts_created_at"),
        "oauth_accounts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_user_id_platform"),
        "oauth_accounts",
        ["user_id", "platform"],
        unique=False,
    )
    # ### end Alembic commands ###
