"""remove revoked at from personal access tokens

Revision ID: e83364fd2be3
Revises: 915b16bdbb5c
Create Date: 2026-08-05 19:04:17.969320

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e83364fd2be3"
down_revision: Union[str, Sequence[str], None] = "915b16bdbb5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_personal_access_tokens_revoked_at"),
        table_name="personal_access_tokens",
    )
    op.drop_column("personal_access_tokens", "revoked_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "personal_access_tokens",
        sa.Column(
            "revoked_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_personal_access_tokens_revoked_at"),
        "personal_access_tokens",
        ["revoked_at"],
        unique=False,
    )
    # ### end Alembic commands ###
