"""add revision to personal access tokens

Revision ID: ff6177c7ea63
Revises: 8ecb7d4b9a0d
Create Date: 2026-07-30 13:57:51.790345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6177c7ea63'
down_revision: Union[str, Sequence[str], None] = '8ecb7d4b9a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_access_tokens', sa.Column('revision', sa.BIGINT(), server_default=sa.text("nextval('revision_number')"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_access_tokens', 'revision')
    # ### end Alembic commands ###
