name: Release

on:
  workflow_call: 
    inputs:
      rinku-image:
        description: "The URI of the Rinku Docker image"
        required: true
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::891924440815:role/github-actions
          aws-region: us-east-1

      - name: Render ECS Task Definition
        id: render
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-arn: arn:aws:ecs:us-east-1:891924440815:task-definition/rinku
          container-name: rinku
          image: ${{ inputs.rinku-image }}

      - name: Run Database Migrations
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render.outputs.task-definition }}
          cluster: rinku
          run-task: true
          run-task-launch-type: FARGATE
          wait-for-task-stopped: true
          run-task-subnets: ${{ vars.ECS_PRIVATE_SUBNETS }}
          run-task-security-groups: ${{ vars.ECS_SECURITY_GROUP }}
          run-task-container-overrides: |
            [
              {
                "name": "rinku",
                "command": ["uv", "run", "task", "db_migrate"]
              }
            ]
      
      - name: Deploy ECS Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render.outputs.task-definition }}
          cluster: rinku
          service: rinku
          wait-for-service-stability: true
